version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: chatgpt_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "9000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    build: 
      dockerfile: ./dockerized/backend/Dockerfile
    container_name: chatgpt_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USER : postgres
      DATABASE_NAME: ${DATABASE_NAME}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  frontend:
    build:
      dockerfile: ./dockerized/frontend/Dockerfile
    container_name: chatgpt_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8501:8501"
    environment:
      FRONTEND_TARGET : backend

volumes:
  postgres_data:
