version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: chatgpt_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    build: 
      context: ..
      dockerfile: dockerized/backend/Dockerfile
    container_name: chatgpt_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  frontend:
    build:
      context: ..
      dockerfile: dockerized/frontend/Dockerfile
    container_name: chatgpt_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8501:8501"
    env_file:
      - ./.env

volumes:
  postgres_data:
